@startuml
skinparam classAttributeIconSize 0
skinparam class {
         BorderColor Navy
         ArrowColor Navy
         BackgroundColor WhiteSmoke
}


title Class diagram

class class {
}

class "class 2" {
}
^
class -right--> "class 2" : > use


hide empty members

@enduml
